### ISSUE TITLE
SveaResponse (Hosted) Crashes

### ISSUE THREAD

**Issue by Tazer** [sveawebpay/dotnet-integration#20]
Hello,

It's a problem when getting back a SveaResponse, With a "invalidtransaction" xml tag.

For example:
PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz48cmVzcG9uc2U+PGludmFsaWR0cmFuc2FjdGlvbj48Y3VzdG9tZXJyZWZubz5PcmRlck5yOjU0NDQ2LTk0MjdjMzUyMWY3YjQ4NzQ5ZWNkOWU4YTYzZmM2NjUzPC9jdXN0b21lcnJlZm5vPjwvaW52YWxpZHRyYW5zYWN0aW9uPjxzdGF0dXNjb2RlPjMyNTwvc3RhdHVzY29kZT48L3Jlc3BvbnNlPg==  

Result in this XML.
```xml
<?xml version="1.0" encoding="UTF-8"?><response><invalidtransaction><customerrefno>OrderNr:54446-9427c3521f7b48749ecd9e8a63fc6653</customerrefno></invalidtransaction><statuscode>325</statuscode></response>
```

**Comment by kilskrift** [comment]
It's been a while, so I'll just note that documentation on the various response url:s is available in the java package documentation, section 3.5.3: http://sveawebpay.github.io/java-integration/#i35
