### ISSUE TITLE
Handling response in return url

### ISSUE THREAD

**Issue by paradisehuman** [sveawebpay/dotnet-integration#22]
How Can I handle response in return url?
I mean how to get response parameter and by which class. 
I use mvc.

**Comment by kilskrift** [comment]
For hosted responses, the received callback response must be parsed through the SveaResponse handler class to receive an inspectable response object containing the hosted service response.

For details, please refer to section 10. Response handler in the documentation at 
https://github.com/sveawebpay/dotnet-integration/tree/master#10-response-handler, and the corresponding package class.

/kgm
