### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by kwestground** [sveawebpay/dotnet-integration#24]
Would be great if you could add dotnet-integration to nuget.org

**Comment by bobinush** [comment]
Any comment on this suggestion guys?

**Comment by fre-sund** [comment]
Hi, sorry for the late response(better late, than never :) ).

I've added it on my todo list.

**Comment by fre-sund** [comment]
It seem's that NuGet doesn't support organizations, but according to their GitHub issue page they are working on it right now: https://github.com/NuGet/NuGetGallery/issues/4627

I've subscribed to the issue and will upload it to NuGet once it's fixed on their side.

**Comment by fre-sund** [comment]
It seem's that NuGet doesn't support organizations, but according to their GitHub issue page they are working on it right now: NuGet/NuGetGallery#4627

I've subscribed to the issue and will upload it to NuGet once it's fixed on their side.

**Comment by itssimple** [comment]
@fre-sund They've released organization support now. :)

**Comment by fre-sund** [comment]
I will take a look at it. :)

**Comment by fre-sund** [comment]
@itssimple It's published on NuGet now. :) https://www.nuget.org/packages/Webpay.Integration.CSharp/

Closing this issue.
