### ISSUE TITLE
"CardType" missing in Webpay.Integration.CSharp.Hosted.Admin.Response.QueryResponse

### ISSUE THREAD

**Issue by henkish** [sveawebpay/dotnet-integration#29]
Property "CardType" exists in your legacy client lib Webpay.EPayment.Integration 2.4.0.0 - but missing in dotnet-integration source. We use this property and need it - can you please add it to the source code?

We use it from the response when querying using QueryByCustomerRefNo.

**Comment by henkish** [comment]
Proposed fix in pull request: https://github.com/sveawebpay/dotnet-integration/pull/32

**Comment by fre-sund** [comment]
Closing this as pull request #32 is merged.
