### ISSUE TITLE
StatusCode not exposed in Webpay.Integration.CSharp.Response.Hosted.SveaResponse

### ISSUE THREAD

**Issue by henkish** [sveawebpay/dotnet-integration#30]
SveaResponse only exposes ResultCode as a formatted string - we need access to the raw (int32) status code from the XML. Please add StatusCode property!

**Comment by henkish** [comment]
Proposed fix in pull request: https://github.com/sveawebpay/dotnet-integration/pull/32

**Comment by fre-sund** [comment]
Closing this as pull request #32 is merged.
