### ISSUE TITLE
Invalid url when using HostedAdmin, SveaConfig.GetProdHostedAdminUrl() and QueryByCustomerRefNo

### ISSUE THREAD

**Issue by henkish** [sveawebpay/dotnet-integration#31]
```
var hostedAdmin = new HostedAdmin(config, countryCode);
var request = hostedAdmin.Query(new QueryByCustomerRefNo(orderId));
var sveaResponse = request.DoRequest<QueryResponse>();
```

When config.GetEndPoint() implementation returns SveaConfig.GetProdHostedAdminUrl() - the URL that gets queried is /rest/rest

**Comment by henkish** [comment]
public string GetEndPoint(PaymentType type)
{
    return _testMode 
        ? SveaConfig.GetTestPayPageUrl().Replace("/rest", "") 
        : SveaConfig.GetProdHostedAdminUrl().Replace("/rest", "");
}

Works, but is a hack

**Comment by fre-sund** [comment]
Fixed in https://github.com/sveawebpay/dotnet-integration/releases/tag/1.0.8

Thanks for the report!
