### ISSUE TITLE
Net standard

### ISSUE THREAD

**Issue by matengo** [sveawebpay/dotnet-integration#38]
Is there any way that this could be targeted Net standard so that it can be used in .Net Core?

**Comment by ornfelt** [comment]
The project has now been upgraded to .net 8 and is hence compatible with .NET core. I've also added a sample shop for demonstrating usage with Invoice, PaymentPlan and AccountCredit payment methods. The SDK code has also undergone some general cleanup and formatting adjustments - the structure and implementation details largely remains the same.
